[package]
authors = ["vuwints <vuwints.me@gmail.com>"]
edition = "2018"
name = "heat"
version = "0.1.0"

[lib]
name = "heat"
path = "src/lib.rs"

[[bin]]
name = "heat"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.38"
arrayvec = "0.5.2"
crossbeam-queue = "0.3.1"
dirs = "3.0"
easy-parallel = "3.1.0"
gpui = {path = "../gpui"}
ignore = {git = "https://github.com/zed-industries/ripgrep", rev = "1d152118f35b3e3590216709b86277062d79b8a0"}
lazy_static = "1.4.0"
libc = "0.2"
log = "0.4"
num_cpus = "1.13.0"
parking_lot = "0.11.1"
rand = "0.8.3"
simplelog = "0.9"
smallvec = "1.6.1"
smol = "1.2.5"

[dev-dependencies]
unindent = "0.1.7"